### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by NotSoMik** [Greensky-gs/hangman#1]
Since this code is so clean and Cool can you update it by adding a dropdown menu where you can choose the letters and also an hangman image which changes depending on whether the answer given is right or wrong

**Comment by Greensky-gs** [comment]
That's a good idea, I didn't made this earlier because I didn't had time.

About the selector, it's a good idea too, but it's more complicated because of max limit of options in a selector, which is 24, so It need a little more lines but it is realisable.

I'll do it asap, I'll tell you when finished on the support server 😀 @NotSoMik

**Comment by NotSoMik** [comment]
Thank you so much 😁
